---
cicd_for_network_automation:
  speakers: victor da costa and ajay chenmpara
  other_notes:
    - gitnetops <- new one for me
    - TETRIS logo? it's red.
    - https://github.com/network-automation/netdevops
  motivation:
    - trace: [who, what, when, why]
    - enforce: [linting, policies, standards, good practices]
    - test: integration in partial and full topologies
    - reduce: [paperwork, time-to-release, human errors]
    - improve: [operations, flexibility, agility, adaptability]
    - scale: apply the same process and tooling from few to hundrews and thousands
  inf_as_code:
    - inf as yaml
    - specs + implementation = desired intent
    - github.com/ansible-network/content_store
  evolution:
    - basic: backup configs to git repo
    - inf as code: pull requests mainly from the team members.. requests for change coming from external systems
    - git centric: pull requests from other teams... git is the tool for requests, changes, and approvals
    - automatic: PR are validated, promoted, and released automatically with extensive tests.. what is request for changes?
  branch_convention:
    release-x.y.z:
    master: latest stable release
    full: entire topology test branch
    site-x: partial topology test branch
    issue-123: feature branch to fix an issue
  fail_fast_test_often:
    - "{{repo}}/tests/test.yaml"
  ci:
    - they have a provisioner that stands up a partial topology as virtual machines
